name: myenv
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - absl-py=0.11.0=py37h89c1867_0
  - aiohttp=3.7.3=py37h4abf009_0
  - async-timeout=3.0.1=py_1000
  - attrs=20.3.0=pyhd3deb0d_0
  - blas=1.0=mkl
  - blinker=1.4=py_1
  - blosc=1.20.1=hd408876_0
  - brotli=1.0.9=he6710b0_2
  - brotlipy=0.7.0=py37hb5d75c8_1001
  - bzip2=1.0.8=h7b6447c_0
  - c-ares=1.17.1=h36c2ea0_0
  - ca-certificates=2020.10.14=0
  - cachetools=4.1.1=py_0
  - cairo=1.14.12=h8948797_3
  - certifi=2020.12.5=py37h06a4308_0
  - cffi=1.14.4=py37h261ae71_0
  - chardet=3.0.4=py37he5f6b98_1008
  - charls=2.1.0=he6710b0_2
  - click=7.1.2=pyh9f0ad1d_0
  - cloudpickle=1.6.0=py_0
  - cryptography=3.2.1=py37hc72a4ac_0
  - cudatoolkit=10.0.130=0
  - cycler=0.10.0=py37_0
  - cytoolz=0.11.0=py37h7b6447c_0
  - dask-core=2.30.0=py_0
  - decorator=4.4.2=py_0
  - ffmpeg=4.0=hcdf2ecd_0
  - fontconfig=2.13.0=h9420a91_0
  - freeglut=3.0.0=hf484d3e_5
  - freetype=2.10.4=h5ab3b9f_0
  - giflib=5.1.4=h14c3975_1
  - glib=2.66.1=h92f7085_0
  - google-auth=1.23.0=pyhd8ed1ab_0
  - google-auth-oauthlib=0.4.1=py_2
  - graphite2=1.3.14=h23475e2_0
  - grpcio=1.33.2=py37haffed2e_2
  - harfbuzz=1.8.8=hffaf4a1_0
  - hdf5=1.10.2=hba1933b_1
  - icu=58.2=he6710b0_3
  - idna=2.10=pyh9f0ad1d_0
  - imagecodecs=2020.5.30=py37hfa7d478_2
  - imageio=2.9.0=py_0
  - importlib-metadata=3.1.1=pyhd8ed1ab_0
  - intel-openmp=2020.2=254
  - jasper=2.0.14=h07fcdf6_1
  - jpeg=9b=h024ee3a_2
  - jxrlib=1.1=h7b6447c_2
  - kiwisolver=1.3.0=py37h2531618_0
  - lcms2=2.11=h396b838_0
  - ld_impl_linux-64=2.33.1=h53a641e_7
  - libaec=1.0.4=he6710b0_1
  - libedit=3.1.20191231=h14c3975_1
  - libffi=3.3=he6710b0_2
  - libgcc-ng=9.1.0=hdf63c60_0
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libglu=9.0.0=hf484d3e_1
  - libopencv=3.4.2=hb342d67_1
  - libopus=1.3.1=h7b6447c_0
  - libpng=1.6.37=hbc83047_0
  - libprotobuf=3.13.0.1=h8b12597_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libtiff=4.1.0=h2733197_1
  - libuuid=1.0.3=h1bed415_2
  - libvpx=1.7.0=h439df22_0
  - libwebp=1.0.1=h8e7db2f_0
  - libxcb=1.14=h7b6447c_0
  - libxml2=2.9.10=hb55368b_3
  - libzopfli=1.0.3=he6710b0_0
  - lz4-c=1.9.2=heb0550a_3
  - markdown=3.3.3=pyh9f0ad1d_0
  - matplotlib-base=3.3.2=py37h817c723_0
  - mkl=2020.2=256
  - mkl-service=2.3.0=py37he8ac12f_0
  - mkl_fft=1.2.0=py37h23d657b_0
  - mkl_random=1.1.1=py37h0573a6f_0
  - multidict=4.7.5=py37h8f50634_2
  - ncurses=6.2=he6710b0_1
  - networkx=2.5=py_0
  - ninja=1.10.2=py37hff7bd54_0
  - numpy=1.19.2=py37h54aff64_0
  - numpy-base=1.19.2=py37hfa32c7d_0
  - oauthlib=3.0.1=py_0
  - olefile=0.46=py37_0
  - opencv=3.4.2=py37h6fd60c2_1
  - openjpeg=2.3.0=h05c96fa_1
  - openssl=1.1.1h=h7b6447c_0
  - pandas=1.1.3=py37he6710b0_0
  - pcre=8.44=he6710b0_0
  - pillow=8.0.1=py37he98fc37_0
  - pip=20.3.1=py37h06a4308_0
  - pixman=0.40.0=h7b6447c_0
  - protobuf=3.13.0.1=py37he6710b0_1
  - py-opencv=3.4.2=py37hb342d67_1
  - pyasn1=0.4.8=py_0
  - pyasn1-modules=0.2.7=py_0
  - pycparser=2.20=pyh9f0ad1d_2
  - pyjwt=1.7.1=py_0
  - pyopenssl=20.0.0=pyhd8ed1ab_0
  - pyparsing=2.4.7=py_0
  - pysocks=1.7.1=py37he5f6b98_2
  - python=3.7.9=h7579374_0
  - python-dateutil=2.8.1=py_0
  - python_abi=3.7=1_cp37m
  - pytorch=1.4.0=py3.7_cuda10.0.130_cudnn7.6.3_0
  - pytz=2020.4=pyhd3eb1b0_0
  - pywavelets=1.1.1=py37h7b6447c_2
  - pyyaml=5.3.1=py37h7b6447c_1
  - readline=8.0=h7b6447c_0
  - requests=2.25.0=pyhd3deb0d_0
  - requests-oauthlib=1.3.0=pyh9f0ad1d_0
  - rsa=4.6=pyh9f0ad1d_0
  - scikit-image=0.17.2=py37hdf5156a_0
  - scipy=1.5.2=py37h0b6359f_0
  - setuptools=51.0.0=py37h06a4308_2
  - six=1.15.0=py37h06a4308_0
  - snappy=1.1.8=he6710b0_0
  - sqlite=3.33.0=h62c20be_0
  - tensorboard=2.4.0=pyhd8ed1ab_0
  - tensorboard-plugin-wit=1.7.0=pyh9f0ad1d_0
  - tifffile=2020.12.4=pyhd3eb1b0_0
  - tk=8.6.10=hbc83047_0
  - toolz=0.11.1=py_0
  - torchvision=0.5.0=py37_cu100
  - tornado=6.1=py37h27cfd23_0
  - tqdm=4.54.1=pyhd3eb1b0_0
  - typing-extensions=3.7.4.3=0
  - typing_extensions=3.7.4.3=py_0
  - urllib3=1.25.11=py_0
  - werkzeug=1.0.1=pyh9f0ad1d_0
  - wheel=0.36.1=pyhd3eb1b0_0
  - xz=5.2.5=h7b6447c_0
  - yaml=0.2.5=h7b6447c_0
  - yarl=1.6.3=py37h4abf009_0
  - zipp=3.4.0=py_0
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.4.5=h9ceee32_0
prefix: /home/esw0116/anaconda3/envs/dynavsr
